"""empty message

Revision ID: 60075d31cdd2
Revises: ae046bd75e8d
Create Date: 2019-06-25 13:12:14.275683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60075d31cdd2'
down_revision = 'ae046bd75e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('no_of_days', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['calendar_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_holidays')
    # ### end Alembic commands ###
