"""empty message

Revision ID: 9e97946fb968
Revises: f488edba3eb6
Create Date: 2019-06-25 13:00:27.612580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e97946fb968'
down_revision = 'f488edba3eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('year', table_name='calendar_years')
    op.drop_column('calendar_years', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_years', sa.Column('year', sa.DATE(), nullable=False))
    op.create_index('year', 'calendar_years', ['year'], unique=True)
    # ### end Alembic commands ###
