"""empty message

Revision ID: ae046bd75e8d
Revises: 9e97946fb968
Create Date: 2019-06-25 13:01:19.465817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae046bd75e8d'
down_revision = '9e97946fb968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_years', sa.Column('year', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'calendar_years', ['year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_years', type_='unique')
    op.drop_column('calendar_years', 'year')
    # ### end Alembic commands ###
